#ifndef HIKARI_MATH_MACRO_UTILS_DEF__H
#define HIKARI_MATH_MACRO_UTILS_DEF__H
#include <Hikari/Preprocessors.h>
#include <boost/preprocessor.hpp>

#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_BINARY_OP(IDX, OP) ((*this)[IDX] OP lhs[IDX])
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_BINARY_OP_S(IDX, OP) ((*this)[IDX] OP lhs)
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_SUM_OF_BINARY_OP(Z,IDX,OP) BOOST_PP_EXPR_IF(IDX,+) HIKARI_MATH_MACRO_UTILS_IMPL_ELM_BINARY_OP(IDX,OP)
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_UNARY_FUNC(Z, IDX, FNC)  BOOST_PP_COMMA_IF(IDX) FNC(lhs[IDX])
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_BINARY_FUNC(Z, IDX, FNC) BOOST_PP_COMMA_IF(IDX) FNC(lhs1[IDX], lhs2[IDX])
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_BINARY_FUNC_S1(Z, IDX, FNC) BOOST_PP_COMMA_IF(IDX) FNC(lhs1, lhs2[IDX])
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_BINARY_FUNC_S2(Z, IDX, FNC) BOOST_PP_COMMA_IF(IDX) FNC(lhs1[IDX], lhs2)
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_TERNARY_FUNC(Z, IDX, FNC)  BOOST_PP_COMMA_IF(IDX) FNC(lhs1[IDX], lhs2[IDX], lhs3[IDX])
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_TERNARY_FUNC_S2_S3(Z, IDX, FNC)  BOOST_PP_COMMA_IF(IDX) FNC(lhs1[IDX], lhs2, lhs3)
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_ARITH(Z,IDX,OP) BOOST_PP_COMMA_IF(IDX) (lhs1[IDX] OP lhs2[IDX])
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_ARITH_S_1(Z,IDX,OP) BOOST_PP_COMMA_IF(IDX) (lhs1 OP lhs2[IDX])
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_ARITH_S_2(Z,IDX,OP) BOOST_PP_COMMA_IF(IDX) (lhs1[IDX] OP lhs2)
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_ARITH_ASSIGN(Z,IDX,OP) (*this)[IDX] OP lhs[IDX];
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_ARITH_ASSIGN_S(Z,IDX,OP) (*this)[IDX] OP lhs;
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_ANDS_OF_COMPARE(Z, IDX, OP) BOOST_PP_EXPR_IF(IDX,&&) ((*this)[IDX] OP lhs[IDX])
#define HIKARI_MATH_MACRO_UTILS_IMPL_ELM_ORS_OF_COMPARE(Z, IDX, OP)  BOOST_PP_EXPR_IF(IDX,||) ((*this)[IDX] OP lhs[IDX])

#define HIKARI_MATH_MACRO_UTILS_IMPL_UNARY_FUNC(TYPE, NUM, FNC, OUT_DECO) \
	template<typename T> OUT_DECO TYPE##<T> FNC(const TYPE##<T>& lhs) noexcept { \
		return TYPE##<T>( BOOST_PP_REPEAT(NUM, HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_UNARY_FUNC, FNC) ); \
	}
#define HIKARI_MATH_MACRO_UTILS_IMPL_BINARY_FUNC(TYPE, NUM, FNC, OUT_DECO) \
	template<typename T> OUT_DECO TYPE##<T> FNC(const TYPE##<T>& lhs1, const TYPE##<T>& lhs2) noexcept { \
		return TYPE##<T>( BOOST_PP_REPEAT(NUM, HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_BINARY_FUNC, FNC) ); \
	}
#define HIKARI_MATH_MACRO_UTILS_IMPL_BINARY_FUNC_S1(TYPE, NUM, FNC, OUT_DECO) \
	template<typename T> OUT_DECO TYPE##<T> FNC(T lhs1, const TYPE##<T>& lhs2) noexcept { \
		return TYPE##<T>( BOOST_PP_REPEAT(NUM, HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_BINARY_FUNC_S1, FNC) ); \
	}
#define HIKARI_MATH_MACRO_UTILS_IMPL_BINARY_FUNC_S2(TYPE, NUM, FNC, OUT_DECO) \
	template<typename T> OUT_DECO TYPE##<T> FNC(const TYPE##<T>& lhs1,T lhs2) noexcept { \
		return TYPE##<T>( BOOST_PP_REPEAT(NUM, HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_BINARY_FUNC_S2, FNC) ); \
	}
#define HIKARI_MATH_MACRO_UTILS_IMPL_TERNARY_FUNC(TYPE, NUM, FNC, OUT_DECO) \
	template<typename T> OUT_DECO TYPE##<T> FNC(const TYPE##<T>& lhs1, const TYPE##<T>& lhs2, const TYPE##<T>& lhs3) noexcept { \
		return TYPE##<T>( BOOST_PP_REPEAT(NUM, HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_TERNARY_FUNC, FNC) ); \
	}
#define HIKARI_MATH_MACRO_UTILS_IMPL_TERNARY_FUNC_S2_S3(TYPE, NUM, FNC, OUT_DECO) \
	template<typename T> OUT_DECO TYPE##<T> FNC(const TYPE##<T>& lhs1, T lhs2, T lhs3) noexcept { \
		return TYPE##<T>( BOOST_PP_REPEAT(NUM, HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_TERNARY_FUNC_S2_S3, FNC) ); \
	}
#define HIKARI_MATH_MACRO_UTILS_IMPL_OP_ARITH_ASSIGN(TYPE,NUM,OP, OUT_DECO) \
	HIKARI_CXX14_CONSTEXPR TYPE##<T>& operator OP(const TYPE##<T>& lhs)noexcept {\
		BOOST_PP_REPEAT(NUM,HIKARI_MATH_MACRO_UTILS_IMPL_ELM_ARITH_ASSIGN, OP) return *this; \
	}
#define HIKARI_MATH_MACRO_UTILS_IMPL_OP_ARITH_ASSIGN_S(TYPE,NUM,OP, OUT_DECO) \
	HIKARI_CXX14_CONSTEXPR TYPE##<T>& operator OP(T lhs)noexcept {\
		BOOST_PP_REPEAT(NUM,HIKARI_MATH_MACRO_UTILS_IMPL_ELM_ARITH_ASSIGN_S, OP) return *this; \
	}
#define HIKARI_MATH_MACRO_UTILS_IMPL_OP_ARITH(TYPE,NUM,OP, OUT_DECO) \
	template<typename T> OUT_DECO auto operator OP (const TYPE##<T>& lhs1, const TYPE##<T>& lhs2) noexcept -> TYPE##<T> { \
		return TYPE##<T>( BOOST_PP_REPEAT(NUM,HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_ARITH, OP) ); \
	}
#define HIKARI_MATH_MACRO_UTILS_IMPL_OP_ARITH_S_1(TYPE,NUM,OP, OUT_DECO) \
	template<typename T> OUT_DECO auto operator OP (T lhs1, const TYPE##<T>& lhs2) noexcept -> TYPE##<T> { \
		return TYPE##<T>( BOOST_PP_REPEAT(NUM,HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_ARITH_S_1,OP) ); \
	}
#define HIKARI_MATH_MACRO_UTILS_IMPL_OP_ARITH_S_2(TYPE,NUM,OP, OUT_DECO) \
	template<typename T> OUT_DECO auto operator OP (const TYPE##<T>& lhs1, T lhs2) noexcept -> TYPE##<T> { \
		return TYPE##<T>( BOOST_PP_REPEAT(NUM,HIKARI_MATH_MACRO_UTILS_IMPL_ELM_LIST_OF_ARITH_S_2,OP) ); \
	}
#define HIKARI_MATH_MACRO_UTILS_IMPL_OP_EQUALITY(TYPE, NUM, OUT_DECO) \
	OUT_DECO bool operator !=(const TYPE##<T>& lhs) const noexcept { \
		return BOOST_PP_REPEAT(NUM, HIKARI_MATH_MACRO_UTILS_IMPL_ELM_ORS_OF_COMPARE, !=); \
	} \
	OUT_DECO bool operator ==(const TYPE##<T>& lhs) const noexcept { \
		return !(*this!=lhs); \
	}
#endif